import type { GuardianConfig } from "./config.js";

export interface CallerWorkflowOptions {
  guardianRepository: string;
  workflowSha: string;
  defaultBranch: string;
  scannerMode: GuardianConfig["scanners"]["mode"];
  image?: GuardianConfig["image"];
  dast?: GuardianConfig["dast"];
}

export function generateCallerWorkflow(options: CallerWorkflowOptions): string {
  const securitySchedule = "23 2 * * *";
  const dastSmokeSchedule = "*/15 * * * *";
  const dastNightlySchedule = "47 2 * * *";
  const reference = `${options.guardianRepository}/.github/workflows/reusable-security.yml@${options.workflowSha}`;
  const imageReference = `${options.guardianRepository}/.github/workflows/reusable-image.yml@${options.workflowSha}`;
  const dastReference = `${options.guardianRepository}/.github/workflows/reusable-dast.yml@${options.workflowSha}`;
  const image = options.image;
  const dast = options.dast;
  const runtimeEnvironment = image?.runtimeEnvironment
    ? Object.entries(image.runtimeEnvironment).map(([key, value]) => `          ${key}=${value}`).join("\n")
    : "";
  const imageJob = image ? `
  guardianbot-image:
    name: guardianbot/image-security
    if: github.event_name != 'schedule' || github.event.schedule == '${securitySchedule}'
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ${imageReference}
    with:
      dockerfile: ${JSON.stringify(image.dockerfile)}
      context: ${JSON.stringify(image.context)}
      image-name: ${JSON.stringify(image.registry)}
      health-path: ${JSON.stringify(image.healthPath)}
      readiness-path: ${JSON.stringify(image.readinessPath ?? "")}
      container-port: ${image.containerPort ?? 8000}
      dependent-services: ${JSON.stringify((image.dependentServices ?? []).join(","))}
      ephemeral-env-keys: ${JSON.stringify((image.ephemeralEnvironment ?? []).join(","))}
      policy-mode: ${JSON.stringify(options.scannerMode)}
      runtime-env: |
${runtimeEnvironment || "          # No runtime environment values configured."}
      migration-command: ${JSON.stringify(image.migrationCommand ?? "")}
      smoke-command: ${JSON.stringify(image.testCommand ?? "")}
      push: ${options.scannerMode === "enforce" ? `\${{ github.event_name == 'push' && github.ref == 'refs/heads/${options.defaultBranch}' }}` : "false"}
` : "";
  const dastJobs = dast ? `
  guardianbot-dast-smoke:
    name: guardianbot/dast-smoke
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.event.schedule == '${dastSmokeSchedule}')
    permissions:
      contents: read
      id-token: write
    uses: ${dastReference}
    with:
      target-origin: ${JSON.stringify(dast.allowedOrigin)}
      openapi: ${JSON.stringify(dast.openapi)}
      openapi-source: ${JSON.stringify(dast.openapiSource ?? (dast.openapi.startsWith("/") || /^https:/i.test(dast.openapi) ? "live-endpoint" : "repository-file"))}
      authentication-profile: ${JSON.stringify(dast.authenticationProfile)}
      session-assertion-path: ${JSON.stringify(dast.sessionAssertionPath)}
      excluded-routes: ${JSON.stringify(JSON.stringify(dast.excludedRoutes ?? []))}
      scan-profile: ${JSON.stringify(dast.profiles?.deploySmoke ?? "authenticated-baseline")}
      minutes: 15

  guardianbot-dast-nightly:
    name: guardianbot/dast-nightly
    if: github.event_name == 'schedule' && github.event.schedule == '${dastNightlySchedule}'
    permissions:
      contents: read
      id-token: write
    uses: ${dastReference}
    with:
      target-origin: ${JSON.stringify(dast.allowedOrigin)}
      openapi: ${JSON.stringify(dast.openapi)}
      openapi-source: ${JSON.stringify(dast.openapiSource ?? (dast.openapi.startsWith("/") || /^https:/i.test(dast.openapi) ? "live-endpoint" : "repository-file"))}
      authentication-profile: ${JSON.stringify(dast.authenticationProfile)}
      session-assertion-path: ${JSON.stringify(dast.sessionAssertionPath)}
      excluded-routes: ${JSON.stringify(JSON.stringify(dast.excludedRoutes ?? []))}
      scan-profile: ${JSON.stringify(dast.profiles?.nightly ?? "authenticated-full")}
      minutes: 45
` : "";
  const schedules = [
    securitySchedule,
    ...(dast ? [dastSmokeSchedule, dastNightlySchedule] : [])
  ];
  return `# Generated by guardianctl. Scanner logic remains in ${options.guardianRepository}.
name: GuardianBot

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [${JSON.stringify(options.defaultBranch)}]
  schedule:
${schedules.map((schedule) => `    - cron: ${JSON.stringify(schedule)}`).join("\n")}
  workflow_dispatch:

permissions:
  contents: read

jobs:
  guardianbot-security-gate:
    name: guardianbot/security-gate
    if: github.event_name != 'schedule' || github.event.schedule == '${securitySchedule}'
    permissions:
      contents: read
      security-events: write
      actions: read
      id-token: write
    uses: ${reference}
    with:
      config-path: .guardianbot/config.yml
${imageJob}
${dastJobs}
`;
}

export function renderOnboardingReport(
  repository: string,
  detection: {
    languages: string[];
    packageManagers: string[];
    lockfiles: string[];
    dockerfiles: string[];
    openapi: string[];
    notes: string[];
  },
  scannerMode: GuardianConfig["scanners"]["mode"]
): string {
  const list = (values: string[]) =>
    values.length ? values.map((value) => `\`${value}\``).join(", ") : "None detected";
  return `## GuardianBot onboarding

Repository: \`${repository}\`

| Capability | Detection |
| --- | --- |
| Languages | ${list(detection.languages)} |
| Package managers | ${list(detection.packageManagers)} |
| Lockfiles | ${list(detection.lockfiles)} |
| Dockerfiles | ${list(detection.dockerfiles)} |
| OpenAPI | ${list(detection.openapi)} |

### Rollout

- Scanner mode starts as **${scannerMode}**.
- Existing findings form the initial baseline.
- Enforcement is enabled separately after the observation period.
- GuardianBot infrastructure and model credentials are not copied into this repository.

### Notes

${detection.notes.map((note) => `- ${note}`).join("\n") || "- No warnings."}
`;
}
