import type { GuardianConfig } from "./config.js";

export interface CallerWorkflowOptions {
  guardianRepository: string;
  workflowSha: string;
  defaultBranch: string;
  image?: GuardianConfig["image"];
}

export function generateCallerWorkflow(options: CallerWorkflowOptions): string {
  const reference = `${options.guardianRepository}/.github/workflows/reusable-security.yml@${options.workflowSha}`;
  const imageReference = `${options.guardianRepository}/.github/workflows/reusable-image.yml@${options.workflowSha}`;
  const image = options.image;
  const runtimeEnvironment = image?.runtimeEnvironment
    ? Object.entries(image.runtimeEnvironment).map(([key, value]) => `          ${key}=${value}`).join("\n")
    : "";
  const imageJob = image ? `
  guardianbot-image:
    name: guardianbot/image-security
    uses: ${imageReference}
    with:
      dockerfile: ${JSON.stringify(image.dockerfile)}
      context: ${JSON.stringify(image.context)}
      image-name: ${JSON.stringify(image.registry)}
      health-path: ${JSON.stringify(image.healthPath)}
      readiness-path: ${JSON.stringify(image.readinessPath ?? "")}
      container-port: ${image.containerPort ?? 8000}
      dependent-services: ${JSON.stringify((image.dependentServices ?? []).join(","))}
      runtime-env: |
${runtimeEnvironment || "          # No runtime environment values configured."}
      migration-command: ${JSON.stringify(image.migrationCommand ?? "")}
      smoke-command: ${JSON.stringify(image.testCommand ?? "")}
      push: \${{ github.event_name == 'push' && github.ref == 'refs/heads/${options.defaultBranch}' }}
` : "";
  return `# Generated by guardianctl. Scanner logic remains in ${options.guardianRepository}.
name: GuardianBot

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [${JSON.stringify(options.defaultBranch)}]
  schedule:
    - cron: "23 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read
  packages: write
  id-token: write
  attestations: write

jobs:
  guardianbot-security-gate:
    name: guardianbot/security-gate
    uses: ${reference}
    with:
      config-path: .guardianbot/config.yml
${imageJob}
`;
}

export function renderOnboardingReport(
  repository: string,
  detection: {
    languages: string[];
    packageManagers: string[];
    lockfiles: string[];
    dockerfiles: string[];
    openapi: string[];
    notes: string[];
  }
): string {
  const list = (values: string[]) =>
    values.length ? values.map((value) => `\`${value}\``).join(", ") : "None detected";
  return `## GuardianBot onboarding

Repository: \`${repository}\`

| Capability | Detection |
| --- | --- |
| Languages | ${list(detection.languages)} |
| Package managers | ${list(detection.packageManagers)} |
| Lockfiles | ${list(detection.lockfiles)} |
| Dockerfiles | ${list(detection.dockerfiles)} |
| OpenAPI | ${list(detection.openapi)} |

### Rollout

- Scanner mode starts as **report-only**.
- Existing findings form the initial baseline.
- Enforcement is enabled separately after the observation period.
- GuardianBot infrastructure and model credentials are not copied into this repository.

### Notes

${detection.notes.map((note) => `- ${note}`).join("\n") || "- No warnings."}
`;
}
